export const ADD_MODULE = 'MODULEITEM/ADD_MODULE';
export const ADD_FILE_MODULE = 'MODULEITEM/ADD_FILE_MODULE';
export const ADD_TEXT_MODULE = 'MODULEITEM/ADD_TEXT_MODULE';
export const MODULE_TITLE = 'MODULEITEM/MODULE_TITLE';
export const RESET = 'MODULEITEM/RESET';
export const DELETE_TEXT_MODULE = 'MODULEITEM/DELETE_TEXT_MODULE';
export const INIT = 'MODULEITEM/INIT';
export const RECORD_ID = 'MODULEITEM/RECORD_ID';


