export const ADD_VALUE = 'TEXTMODULE/ADD_VALUE';
export const RESET = 'TEXTMODULE/RESET';
export const INIT = 'TEXTMODULE/INIT';
export const DELETE = 'TEXTMODULE/DELETE';
export const ADD_STATUS = 'TEXTMODULE/ADD_STATUS';
export const CHANGE_TODO_STATUS = 'TEXTMODULE/CHANGE_TODO_STATUS';
export const DELETE_MODULE = 'TEXTMODULE/DELETE_MODULE';
