export const MODULE_ITEM = 'EDITPROJECT/MODULE_ITEM';
// export const TEXT_MODULE_ITEM = 'EDITPROJECT/TEXT_MODULE_ITEM';
// export const FILE_MODULE_ITEM = 'EDITPROJECT/FILE_MODULE_ITEM';
export const PROJECT_TITLE = 'EDITPROJECT/PROJECT_TITLE';

