export const MODULE_ITEM = 'EDITPROJECT/MODULE_ITEM';
export const PROJECT_TITLE = 'EDITPROJECT/PROJECT_TITLE';
export const RESET = 'EDITPROJECT/RESET';
export const INIT = 'EDITPROJECT/INIT';
export const RECORD_MODULE_ID = 'EDITPROJECT/RECORD_MODULE_ID';
export const DELETE_MODULE = 'EDITPROJECT/DELETE_MODULE';

