export const ADD_FILE = 'FILEMODULE/ADD_FILE';
export const IS_OPEN_MODAL = 'FILEMODULE/IS_OPEN_MODAL';
export const RESET = 'FILEMODULE/RESET';
export const DELETE = 'FILEMODULE/DELETE';
export const INIT = 'FILEMODULE/INIT';
export const CHANGE_TODO_STATUS = 'FILEMODULE/CHANGE_TODO_STATUS';

